version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: mysql_db
    restart: always
    environment: 
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: books
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  springboot_app:
    build: .
    container_name: springboot_app
    restart: always
    ports:
      - "1001:1001"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/books?serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
    depends_on:
      - mysql

volumes:
  mysql_data:

